# Generated by Django 5.1.4 on 2025-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='direction',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='outcome',
            field=models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Breakeven', 'Breakeven')], max_length=50),
        ),
    ]
