# Generated by Django 5.1.4 on 2025-03-13 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_journalentry_images_journalentry_profit_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='feeling_during',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
