# Generated by Django 5.2 on 2025-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='feeling_during',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='feeling_before',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='feeling_during_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of account risked on this trade', max_digits=5, null=True),
        ),
    ]
