# Generated by Django 5.2 on 2025-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_journalentry_feeling_during_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='max_risk',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum risk percentage allowed per trade', max_digits=5),
        ),
    ]
