# Generated by Django 5.2 on 2025-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_journal_max_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='follow_strategy',
            field=models.BooleanField(default=True, help_text='Did you follow your trading strategy for this trade?'),
        ),
    ]
