# Generated by Django 5.2 on 2025-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('followed_plan', 'Followed Plan'), ('journal_trade', 'Journal Trade'), ('high_rating', 'High Rating'), ('profitable_day', 'Profitable Day')], max_length=50),
        ),
    ]
