# Generated by Django 5.2 on 2025-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_milestone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='account_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial account size for calculating position sizes', max_digits=12, null=True),
        ),
    ]
