# Generated by Django 5.2 on 2025-04-30 15:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_journal_account_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('instrument', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=50)),
                ('outcome', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Breakeven', 'Breakeven')], max_length=50)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feeling_before', models.CharField(blank=True, choices=[('Hesitant', 'Hesitant'), ('Slightly hesitant', 'Slightly hesitant'), ('Neutral', 'Neutral'), ('Slightly confident', 'Slightly confident'), ('Very confident', 'Very confident')], max_length=50, null=True)),
                ('confidence_before', models.IntegerField(blank=True, null=True)),
                ('feeling_during', models.CharField(blank=True, choices=[('Very worried', 'Very worried'), ('Worried', 'Worried'), ('Slightly worried', 'Slightly worried'), ('Neutral', 'Neutral'), ('Slightly confident', 'Slightly confident'), ('Very confident', 'Very confident')], max_length=50, null=True)),
                ('confidence_during', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_copies', to='api.journalentry')),
                ('original_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_entries', to='api.journal')),
            ],
        ),
    ]
