# Generated by Django 5.2 on 2025-05-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_score'),
        ('api', 'create_missing_profiles'),
    ]

    operations = [
    ]
