# Generated by Django 5.2 on 2025-05-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_0016_userprofile_score_create_missing_profiles'),
        ('api', 'fix_points_to_score'),
    ]

    operations = [
    ]
